project_id: "834654"
api_token_env: CROWDIN_PERSONAL_TOKEN

files:
  - source: /lang/en.json
    translation: /lang/%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        de: de      # German - bereits vorhanden
        fr: fr      # French
        es: es      # Spanish
        pt: pt      # Portuguese
        nl: nl      # Dutch
        it: it      # Italian
        pl: pl      # Polish
        tr: tr      # Turkish
        ru: ru      # Russian
        ja: ja      # Japanese
        ko: ko      # Korean
        zh-CN: zh   # Chinese (Simplified)
    # Nur vollständig übersetzte Strings herunterladen
    export_only_approved: false
    skip_untranslated_strings: true
    # Übersetzungen in Git-freundlichem Format (sortiert, eingerückt)
    export_languages:
      - de      # German
      - fr      # French
      - es      # Spanish
      - pt      # Portuguese
      - nl      # Dutch
      - it      # Italian
      - pl      # Polish
      - tr      # Turkish
      - ru      # Russian
      - ja      # Japanese
      - ko      # Korean
      - zh      # Chinese
